AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  stardew

  Sample SAM Template for stardew

Resources:
  VoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../vote/
      Handler: vote.lambda_handler
      Runtime: python3.7
      Timeout: 30
        Policies:
            - Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:UpdateItem
                  Resource:
                    -
                      Fn::ImportValue: "StardewViewersStateTableArn"
                    -
                      Fn::ImportValue: "StardewVotesStateTableArn"
      Environment:
        Variables:
          VOTE_TABLE:
            Fn::ImportValue: "StardewVotesStateTableName"
          VIEWERS_TABLE:
            Fn::ImportValue: "StardewViewersStateTableName"
      Events:
        Post:
          Type: 'Api'
          Properties:
            Path: '/'
            Method: 'vote'

  WeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../weather/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 30
        Policies:
            - Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                  Resource:
                    Fn::ImportValue: "StardewWeatherStateTableArn"
      Environment:
        Variables:
          WEATHER_TABLE:
            Fn::ImportValue: "StardewWeatherStateTableName"
      Events:
        Get:
          Type: 'Api'
          Properties:
            Path: '/'
            Method: 'current_weather'

  ProcessWinnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../winner/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 30
        Policies:
            - Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:Query
                  Resource:
                    Fn::ImportValue: "StardewVotesStateTableArn"
                - Effect: Allow
                  Action:
                    - dynamodb:UpdateItem
                  Resource:
                    Fn::ImportValue: "StardewWeatherStateTableArn"
      Environment:
        Variables:
          WEATHER_TABLE:
            Fn::ImportValue: "StardewWeatherStateTableName"
          VOTE_TABLE:
            Fn::ImportValue: "StardewVotesStateTableName"

  ProcessnewVoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../vote/
      Handler: new_vote.lambda_handler
      Runtime: python3.7
      Timeout: 30
        Policies:
            - Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:UpdateItem
                  Resource:
                    Fn::ImportValue: "StardewWeatherStateTableArn"
      Environment:
        Variables:
          WEATHER_TABLE:
            Fn::ImportValue: "StardewWeatherStateTableName"

Outputs:
  VoteFunction:
    Description: "Vote Function ARN"
    Value: !GetAtt VoteFunction.Arn
    Export:
      Name: "VoteFunctionArn"